// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utilities} from '../models';

export function GetPartitions():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<utilities.ListingResults>;

export function OpenFile(arg1:string):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<utilities.SearchResult>>;
